// Generated by https://quicktype.io

export interface Review {
	author: string;
	author_details: AuthorDetails;
	content: string;
	created_at: Date;
	id: string;
	updated_at: Date;
	url: string;
}

export interface AuthorDetails {
	name: string;
	username: string;
	avatar_path: string;
	rating: number;
}
